GET http://localhost:3000/api/places
###
POST http://localhost:3000/api/places
Content-Type: application/json

{
    "titulo": "Apartamento de prueba",
    "descripcion": "Esto es para probar las inserciones",
    "tamano": 90,
    "direccion": "Calle Prueba 123",
    "codigoPostal": "28090",
    "precio": 800 
}
###
PUT http://localhost:3000/api/places/2
Content-Type: application/json

{
    "titulo": "Apartamento de prueba",
    "descripcion": "Esto es para probar las inserciones",
    "tamano": 30,
    "direccion": "Calle Modificada 123",
    "codigoPostal": "28090",
    "precio": 200 
}
###
DELETE http://localhost:3000/api/places/3